### ISSUE TITLE
Propuesta para campos adicionales en models y eliminacion posible

### ISSUE THREAD

**Issue by katou-raiden** [katou-raiden/concurso_mate#2]
**ELIMINAR CAMPO CI:**
Creo que el campo de carnet de identidad hace nada mas que bulto, porque sino es menos cierto que identifica unicamente a la persona, puede resultar engorroso de llenar al que se vaya a registrar en el sitio ... y es inaudito que le puedas presentar un campo para el carnet de identidad como no requerido al usuario (vamos...que se lo puede pasar por alto tan pachangon),  ademas que ya de por si todos los campos, como direccion, ciudad y telefonos, comprometen la privacidad del mismo... no es solo por eso... sino que al ser esto cierto tambien le resulta molesto responderlos. Creo que lo mas correcto seria dejarlo fuera de cuestion.

**ANNADIR CAMPOS SCORE Y REPUTATION:**
Si... asi como dicen sus nombres.. estos serian annadidos tanto usuario como al profesor... estuve pensando hace rato,, que la aplicacion como apunta alto, no solamente tendria la presencia de nuestro gran y estimado profesor "COLORETE" sino tambien otros que contribuirian... por tanto no estaria mal setear tanto una puntuacion y reputacion cuya evaluacion estaria evaluada de manera personalizada para cada uno de los dos roles definidos. La diferencia entre reputacion y puntuacion seria que puntuacion seria la calificacion de la habilidad y conocimiento demostrados por el profesor en examenes preparados y subidos al sitio con antelacion, y reputacion lo demas.

CONCLUSION:
Dime que te parecen todas estas ideas, prefiero que me dejes la respuesta por aqui y me timbres para avisarme... o si estas flojeras pues llamame y discutimos esto, un saludo.

**Comment by lustful-pavorus** [comment]
La eliminación del campo CI me parece bien, igual que los campos Score y Reputación pero no se, no los veo muy claros aún después los discutiremos
